language: python
python:
    - 2.7

services:
    - docker

before_script:
    - cd oq-docker
    - docker build --rm=true -t openquake-centos7 -f Dockerfile.centos .

script:
    - docker run -i -t openquake-centos7 'oq --version'

