language: python
python:
    - 2.7

services:
    - docker

install:
    - cd oq-tests && docker build --rm=true -t oq-centos7 -f oq-centos7/Dockerfile .

script:
    - docker run --rm=true -i -t oq-centos7 

